In [6]:
from google.colab import files
uploaded = files.upload()

Saving 1unb_multi.csv to 1unb_multi.csv


In [7]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the dataset
data = pd.read_csv("1unb_multi.csv")  # Replace with the path to your dataset

# Extract features (X) and label (y)
X = data.iloc[:, 2:]  # Select columns from the 3rd column onwards
y = data.iloc[:, 1]   # Select the 2nd column as the label

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=200, criterion='gini', min_samples_split=2, max_depth=100, random_state=42)

# Train the classifier
rf_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.5f}")


Accuracy: 0.98311


In [8]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import matplotlib.pyplot as plt

# Obtain the confusion matrix on the testing data
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate the accuracy score on the testing data
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Perform cross-validation on the training data
cv_scores = cross_val_score(rf_classifier, X_train, y_train, cv=5)
print("Cross-Validation Scores:")
print(cv_scores)
print("Average Accuracy:", cv_scores.mean())


Confusion Matrix:
[[28927    42    11    75     5]
 [   30 10528     7     1     2]
 [   41    13  3375    31     7]
 [  427    32     9  2439    22]
 [   58     7     4    14  3503]]
Accuracy: 0.9831082443055835
Cross-Validation Scores:
[0.98350035 0.98190143 0.98259254 0.98142629 0.98254935]
Average Accuracy: 0.9823939916172473


In [9]:
# Evaluate the model
accuracy_value = accuracy_score(y_test, y_pred)
classification_report_str = classification_report(y_test, y_pred, digits=5)

# Print the results
print(f'Accuracy: {accuracy_value:.5f}')
print(f'Classification Report:\n{classification_report_str}')

Accuracy: 0.98311
Classification Report:
              precision    recall  f1-score   support

  Defacement    0.98114   0.99542   0.98823     29060
      benign    0.99115   0.99621   0.99368     10568
     malware    0.99090   0.97346   0.98210      3467
    phishing    0.95273   0.83271   0.88869      2929
        spam    0.98983   0.97685   0.98330      3586

    accuracy                        0.98311     49610
   macro avg    0.98115   0.95493   0.96720     49610
weighted avg    0.98291   0.98311   0.98273     49610

