In [5]:
from google.colab import files
uploaded = files.upload()


Saving 1unb_multi.csv to 1unb_multi.csv


In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

# Load the CSV file
df = pd.read_csv('1unb_multi.csv')

# Split the dataset into features and labels
X = df.iloc[:, 2:].values  # Assuming the features start from the third column
y = df['Label'].values
 #Split the dataset into features and labels
#X = df.iloc[:, :-1].values
#y = df.iloc[:, -1].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Encode the features using LabelEncoder
'''label_encoder = LabelEncoder()
for column in X.columns:
    if X[column].dtype == 'object':
        X[column] = label_encoder.fit_transform(X[column].astype(str))

# Encode the labels using LabelEncoder
y = label_encoder.fit_transform(y)'''


# Initialize the decision tree classifier
clf = DecisionTreeClassifier(max_depth=200, criterion='gini', splitter='best')

# Train the model
clf.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=200)

In [10]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import matplotlib.pyplot as plt

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
# Obtain the confusion matrix on the testing data
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Calculate the accuracy score on the testing data
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Perform cross-validation on the training data
cv_scores = cross_val_score(clf, X_train, y_train, cv=5)
print("Cross-Validation Scores:")
print(cv_scores)
print("Average Accuracy:", cv_scores.mean())


Accuracy: 0.9748840959483975
Confusion Matrix:
[[28674    43    54   252    37]
 [   56 10468    24    18     2]
 [   42     7  3364    45     9]
 [  435    24    59  2366    45]
 [   50     6     5    33  3492]]
Accuracy: 0.9748840959483975
Cross-Validation Scores:
[0.97291811 0.97175068 0.97429917 0.97092998 0.97438556]
Average Accuracy: 0.9728566980423615


In [11]:
# Evaluate the model
accuracy_value = accuracy_score(y_test, y_pred)
classification_report_str = classification_report(y_test, y_pred, digits=5)

# Print the results
print(f'Accuracy: {accuracy_value:.5f}')
print(f'Classification Report:\n{classification_report_str}')



Accuracy: 0.97488
Classification Report:
              precision    recall  f1-score   support

  Defacement    0.98007   0.98672   0.98338     29060
      benign    0.99242   0.99054   0.99148     10568
     malware    0.95950   0.97029   0.96486      3467
    phishing    0.87178   0.80778   0.83856      2929
        spam    0.97406   0.97379   0.97392      3586

    accuracy                        0.97488     49610
   macro avg    0.95556   0.94582   0.95044     49610
weighted avg    0.97444   0.97488   0.97458     49610

